defaultPlatforms:
  - linux/arm64
  - linux/amd64
builds:
  - id: main
    dir: .
    main: .
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Git.Tag }}-{{ .Git.ShortCommit }}-{{ .Git.TreeState }}
