name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag to use for the release
        required: true
        type: string
jobs:
  image:
    permissions:
      id-token: write
      contents: read
      attestations: write
    name: build and push oci image (with sbom)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: image
        run: |
          IMAGE_REF=$(make image | tail -n1 | cut -d'@' -f2)
          echo "image_ref=${IMAGE_REF}" >> "$GITHUB_OUTPUT"
    outputs:
      image_ref: ${{ steps.image.outputs.image_ref }}
  attest:
    name: attest artifacts
    runs-on: ubuntu-latest
    needs: image
    steps:
      - uses: actions/attest@v4
        with:
          subject-name: ghcr.io/ihcsim/nad-service-controller
          subject-digest: ${{ needs.image.outputs.image_ref }}
          push-to-registry: true
  #release_page:
