name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag to use for the release
        required: true
        type: string
jobs:
  image:
    permissions:
      contents: read
      packages: write
    name: build and push oci image (with sbom)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: stable
      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445
      - id: build_and_push
        run: |
          #!/bin/bash
          set -euo pipefail
          IMAGE_REF=$(make image-release 2>&1 | tail -n1 | cut -d'@' -f2)
          echo "image_ref=${IMAGE_REF}" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release-artifacts
          path: |
            release.yaml
            sbom/
          if-no-files-found: error
    outputs:
      image_ref: ${{ steps.build_and_push.outputs.image_ref }}
  attest:
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    name: attest artifacts
    runs-on: ubuntu-latest
    needs: image
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest@v4
        with:
          subject-name: ghcr.io/ihcsim/nad-service-controller
          subject-digest: ${{ needs.image.outputs.image_ref }}
          push-to-registry: true
  release_page:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [attest]
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: release-artifacts
          path: dist
      - name: create gh release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          working_directory: dist
          tag_name: ${{ inputs.tag }}
          files: |
            *
